# full definition detekt formatting: https://github.com/detekt/detekt/blob/main/detekt-formatting/src/main/resources/config/config.yml

# https://detekt.dev/docs/rules/comments/
comments:
    CommentOverPrivateFunction:
        active: true
    CommentOverPrivateProperty:
        active: true
    DeprecatedBlockTag:
        active: true
    EndOfSentenceFormat:
        active: true
    KDocReferencesNonPublicProperty:
        active: true
    OutdatedDocumentation:
        active: true

# https://detekt.dev/docs/rules/complexity/
complexity:
    CyclomaticComplexMethod:
        threshold: 11
    LabeledExpression:
        active: true
    LargeClass:
        threshold: 301
    LongMethod:
        threshold: 31
    LongParameterList:
        excludes: [ '**/model/**' ]
    NamedArguments:
        threshold: 1

# https://detekt.dev/docs/rules/coroutines/
coroutines:
    GlobalCoroutineUsage:
        active: true

# https://detekt.dev/docs/rules/formatting/
formatting:
    AnnotationSpacing:
        active: false
    AnnotationOnSeparateLine:
        active: false
    ArgumentListWrapping:
        maxLineLength: 160
    ContextReceiverMapping:
        maxLineLength: 160
    MaximumLineLength:
        maxLineLength: 160
    MultiLineIfElse:
        active: false
    ParameterListWrapping:
        maxLineLength: 160
    PropertyWrapping:
        maxLineLength: 160

# https://detekt.dev/docs/rules/naming/
naming:
    BooleanPropertyNaming:
        active: true
    LambdaParameterNaming:
        active: true
        parameterPattern: '[a-z]+[A-Za-z0-9]{2,}|_'
    MemberNameEqualsClassName:
        active: false
    NonBooleanPropertyPrefixedWithIs:
        active: true

# https://detekt.dev/docs/rules/performance/
performance:
    SpreadOperator:
        active: false
    UnnecessaryPartOfBinaryExpression:
        active: true

# https://detekt.dev/docs/rules/potential-bugs/
potential-bugs:
    MissingPackageDeclaration:
        active: true
    UnnecessaryNotNullCheck:
        active: true
    UnnecessaryNotNullOperator:
        active: true

# https://detekt.dev/docs/rules/style/
style:
    AlsoCouldBeApply:
        active: true
    CanBeNonNullable:
        active: true
    CollapsibleIfStatements:
        active: true
    DoubleNegativeLambda:
        active: true
    EqualsOnSignatureLine:
        active: true
    ExplicitItLambdaParameter:
        active: true
    ExpressionBodySyntax:
        active: true
        includeLineWrapping: false
    ForbiddenComment:
        active: true
    MaxLineLength:
        maxLineLength: 160
    PreferToOverPairSyntax:
        active: true
    TrailingWhitespace:
        active: true
    UnderscoresInNumericLiterals:
        active: true
    UnnecessaryLet:
        active: true
    UntilInsteadOfRangeTo:
        active: true
    UseEmptyCounterpart:
        active: true
